#!/bin/bash

echo "/START"
ID=$(docker run -d "$@")
echo $ID

# Trap signals, run docker stop / docker kill
trap "echo /STOP; docker stop $ID && echo /RM && docker rm -v $ID && echo /EXIT && exit" SIGTERM SIGHUP
trap "echo /KILL; docker kill $ID ;  echo /RM ;  docker rm -v $ID ;  echo /EXIT ;  exit" SIGKILL

# Wait forever
while true; do sleep 1; done
